definitions:
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  v1.ChangePasswordParams:
    properties:
      password:
        type: string
      rePassword:
        type: string
    type: object
  v1.DelParams:
    properties:
      id:
        description: 帮助文档ID
        type: integer
    type: object
  v1.HelpSubmitParams:
    properties:
      h5Link:
        description: 链接
        type: string
      id:
        type: integer
      sort:
        description: 排序
        type: integer
      title:
        description: 标题
        type: string
    type: object
  v1.LoginParams:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    name: API Support
    url: http://www.swagger.io/support
  description: go-gin-swagger 服务后端API接口文档
  title: go-gin-swagger
  version: "1.0"
paths:
  /admin/v1/auth/changePassword:
    post:
      description: 管理员修改密码
      parameters:
      - description: Password 密码 RePassword 再次输入密码
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/v1.ChangePasswordParams'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                code:
                  type: integer
              type: object
      security:
      - Bearer: []
      summary: 修改密码
      tags:
      - 管理员
  /admin/v1/auth/login:
    post:
      description: 管理员登录
      parameters:
      - description: Username:用户名,Password:密码
        in: body
        name: admin
        required: true
        schema:
          $ref: '#/definitions/v1.LoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                code:
                  type: integer
              type: object
      security:
      - Bearer: []
      summary: 登录
      tags:
      - 管理员
  /admin/v1/help/addHelp:
    post:
      description: 新增帮助文档
      parameters:
      - description: Title：标题；H5Link 链接；sort 排序
        in: body
        name: help
        required: true
        schema:
          $ref: '#/definitions/v1.HelpSubmitParams'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                code:
                  type: integer
              type: object
      security:
      - Bearer: []
      summary: 新增
      tags:
      - 帮助文档
  /admin/v1/help/delHelp:
    post:
      description: 帮助文档删除
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: id:帮助文档ID
        in: body
        name: help
        required: true
        schema:
          $ref: '#/definitions/v1.DelParams'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                code:
                  type: integer
              type: object
      security:
      - Bearer: []
      summary: 删除
      tags:
      - 帮助文档
  /admin/v1/help/editHelp:
    post:
      description: 修改帮助文档
      parameters:
      - description: Title：标题；H5Link 链接；sort 排序
        in: body
        name: help
        required: true
        schema:
          $ref: '#/definitions/v1.HelpSubmitParams'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                code:
                  type: integer
              type: object
      security:
      - Bearer: []
      summary: 修改
      tags:
      - 帮助文档
  /admin/v1/help/getHelpList:
    get:
      description: 帮助文档分页列表查询
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: 每页条数
        in: query
        name: pageSize
        type: integer
      - description: 页码
        in: query
        name: pageNo
        type: integer
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                code:
                  type: integer
              type: object
        "400":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                code:
                  type: integer
              type: object
      summary: 列表查询
      tags:
      - 帮助文档
swagger: "2.0"
